### PR TITLE
Shriram

### PR DESCRIPTION
**Pull request by shriram-joshi**
-Completed user registeration work flow for customer and vendor

### CODE REVIEW

**Comment by shriram-joshi** [comment]
[bug]When wrong otp is entered app crashes

**Review by shriram-joshi — COMMENTED** [review]
[bug]On entering wrong OTP app crashes

**Comment by unc0ded** [comment]
Some issues in activity_customer_signup.xml. Will rectify tomorrow and pull.

**Comment by unc0ded** [comment]
Working on getting and displaying vendor data for customer Nearby Vendors tab. When done, will pull from my branch. Already incorporated changes from recent commits from your branch.

**Pull request closed without merging**
